emulator-vcd:
	sbt "run-main McAccel.PearsonHasherMain --compile --genHarness --test --vcd --debug --targetDir build/emulator/generated-src"

emulator:
	sbt "run-main McAccel.PearsonHasherMain --compile --genHarness --targetDir build/emulator/generated-src"
