ROOT_DIR := ..

SVGSRC := frontend.svg kvstore.svg rocket-pipeline.svg \
	system-base.svg system-kvstore.svg \
	dma-rx.svg dma-tx.svg
DOCUMENT := poster.tex

include $(ROOT_DIR)/Makefrag

all: $(DOCUMENT_PDF)
